name: get BTCMAP rank

on:
 workflow_call:
 workflow_dispatch:
 schedule:
   - cron: "30,0 * * * *"
 

jobs:
  genRank:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get BTC MAP Areas
        id: getArea
        if: vars.GETRANK == 'Y'
        run: bash getArea.sh
      - name: Get BTC MAP Rank1
        id: getRank
        run: bash genRank.sh
      - name: Upload to git
        id: uploadGit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "juancolchete"
            git config --global user.email "juancolchete@gmail.com"
            git add . 
            git commit -m "chore: add title ${{github.event.head_commit.message}}"
            git push
          else
            echo "no changes to push"
          fi
